- name: 'Entry Locks'
  description: 'Entry locks are mostly found on external doors although some can be on internal doors as well They are key operated & usally supplied by us keyed alike or keyed to your existing key for your convenience.'
  image: 'assets/images/products/knobset-ant_jpg.jpg'
- name: 'Deadlocks'
  description: 'We offer a large range of deadlocks for many different applications. Whether you need a single cylinder or double cylinder deadlock for a door or gate, we are sure to be able to find the right one for your needs. Most deadlocks can be supplied keyed alike or keyed to your existing key.'
  image: 'assets/images/products/Double-Cylinder-Deadbolt_0.jpg'
- name: 'Window Locks'
  description: 'As there are many different types of windows, so too are there many types of window locks.Whether you have aluminium or timber, sliding, casement or double hung windows we are sure to have the right security lock for you windows.'
  image: 'assets/images/products/sliding%20window%20lock2.jpg'
- name: 'High Quality Leversets'
  description: 'Entry, passage, privacy & dummy levers in all shapes, colours & sizes. We have Polished brass, Antique brass, Bright Chrome, Satin Chrome & even some nickel plated.'
  image: 'assets/images/products/brass%20lever.jpg'
- name: 'Cupboard And Cabinet Hardware'
  description: 'Knobs, handles and pulls of every shape colour and size. Brass, chrome, satin chrome, dual finish and timber. We even have knobs in the shape of basketballs or teddy bears! We also stock various catches to hold your cupboards closed including magnetic, gripper and ball catches.'
  image: 'assets/images/products/knob.jpg'
- name: 'Roll-A-Door Locks'
  description: 'The Xtra-Lok roll-a-door lock is by far one of the best ways to secure your roll-a-door. It locks the door sucurely to the ground resisting the forcing of the door upwards or inwards. It comes in external (pictured) or internal models.'
  image: 'assets/images/products/xtralok.jpg'
- name: 'Safes'
  description: 'Security Safes range greatly from something for the home to keep a little cash, jewelery and papers, to bank quality safes for the business for storage of much larger sums of cash and other goodies (crown jewels perhaps?). There are also many types of rifle and pistol safes available depending on your licence requirements. Give us a call or come in to our showroom today to discuss your needs with one of our helpful staff.'
  image: 'assets/images/products/commander%20cr4.jpg'
- name: 'High Security Padlocks And Chain'
  description: 'When you need to protect your new investment such as a bicycle, motorcycle or boat, a high security padlock and chain is a must. With a top quality padlock and chain you can help keep your new toy safe from the hands of theives.'
  image: 'assets/images/products/83_60.jpg'
- name: 'Door Closers'
  description: "Door closers are another area where there ar many different and varied types. Depending on your door's type, size, weight & whether it's a commercial or domestic door, a suitable door closer will be close at hand. Parralel arm, slide arm, pivot hinge type and the list goes on, let us know what you need and we'll get something for you."
  image: 'assets/images/products/door%20closer.jpg'
- name: 'Commercial Door Hardware'
  description: 'There are many options these days for commercial supply of door furniture and hardware. From mortice locks and levers to door closers and smoke seals, we do it all. Give Mark a call today for some very competetive pricing.'
  image: 'assets/images/products/3572SC_hr.jpg'
- name: 'Hinges'
  description: 'We have a huge range of hinges available to us. Brass, stainless, galvanised & aluminium. Fixed pin, loose pin, bearing assisted, lift off, self closing & many more.'
  image: 'assets/images/products/hinge.jpg'
- name: 'CCTV'
  description: 'From a basic video doorbell to a DIY system you can access on your smart phone, Abus have a great range of monitoring options.'
  image: 'assets/images/products/CC00266%20Wireless%20Camera%20KitCat.jpg'
- name: 'Disabled Grabrails, Toilet Accessories & Signage'
  description: 'Stainless steel grab rails, self adhesive toilet door signs, hand dryers, even toilet roll holders, give us a call for your next commercial project.'
  image: 'assets/images/products/Disabled-sign.jpg'
- name: 'Door Seals: Draught Excluders, Light, Sound & Smoke Seals'
  description: 'Tests have shown that the average gap around a standard entry door is equal to leaving a full house brick out of your wall. We stock all types of door and window seals for domestic and industrial applications.'
  image: 'assets/images/products/seals.jpg'
- name: 'High Security Master Keyed Systems'
  description: "Not only can we provide a key sytem so one key opens all locks & each lock has it's own key but this system can also be restricted. This means work can only be performed under your written authority. No more wondering if someone has had keys cut without you knowing."
  image: 'assets/images/products/ABLOY%20PROTEC%20key.jpg'
- name: 'Keyless Entry'
  description: 'Keyless entry is an excellent way of allowing many users access into your building.'
  image: 'assets/images/products/lockwood_digital_deadbolt.jpg'
